# Generated by Django 3.2.5 on 2021-09-21 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210921_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avatar',
            field=models.ImageField(default=None, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='avatar',
            field=models.ImageField(default=None, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
    ]
